config/routes.rb
require 'sidekiq/web'
Instafix::Application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'sidekiq' && password == 'p1nk3rt0n'
  end 
  mount Sidekiq::Web => '/sidekiq'
  
  resource :session do
    collection do
      get 'callback'
      get 'logout'
    end
  end

  resources :photos do
    collection do
      post 'alter'
      get 'ingest'
      get 'ingest_all'
    end
  end

  resource :static

  match "/about" => "static#about"

  root :to => "static#show"
end

app/models/flickr_fixer.rb
class FlickrFixer
  @queue = :photos_queue

  def self.perform(photo_id, user_id)
    photo = Photo.find(photo_id)
    user = User.find(user_id)

    FlickRaw.api_key = ENV['FLICKR_API_KEY']
    FlickRaw.shared_secret = ENV['FLICKR_SHARED_SECRET']
    flickr = FlickRaw::Flickr.new
    flickr.access_token = user.oauth_token
    flickr.access_secret = user.oauth_token_secret

    flickr.photos.setMeta(:photo_id => photo.flickr_id,
                          :title => photo.title,
                          :description => photo.description)
    flickr.photos.setTags(:photo_id => photo.flickr_id,
                            :tags => photo.taglist)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :flickr_id, :title, :description, :taglist, :is_family, :is_friend, :is_public, :thumb_url, :user_id, :taken_at
  belongs_to :user

  scope :visible, :conditions => {:is_hidden => false}
  scope :hidden, :conditions => {:is_hidden => true}

  def public_web_page
    "http://www.flickr.com/photos/#{self.user.nsid}/#{self.flickr_id}"
  end

  def update_from_photo_hash(photo_hash)
    # update attributes
    self.title = photo_hash["title"]
    self.description = photo_hash["description"]
    self.taglist = photo_hash["taglist"]

    # update hidden
    if photo_hash["is_hidden"] == "1" 
      self.is_hidden = true
    end
    self.save
  end

  def self.ingest_latest_for_user(user)
    since = 1

    if user.photos.any?
      first_photo = user.photos.sort_by(&:taken_at).first
      since = first_photo.taken_at.to_i
    end
    ingest_photos_for_user_since(user, since)
  end

  def self.ingest_all_for_user(user)
    ingest_photos_for_user_since(user,1)
  end

  def self.ingest_photos_for_user_since(user, since)
    FlickRaw.api_key = ENV['FLICKR_API_KEY']
    FlickRaw.shared_secret = ENV['FLICKR_SHARED_SECRET']
    flickr = FlickRaw::Flickr.new

    size = 500
    page = 1
    photolist = []

    while size == 500 do
      results = flickr.photos.search(:user_id => user.nsid, 
                                     :machine_tags => 'uploaded:by="instagram"', 
                                     :extras => 'description,tags,url_q,date_taken',
                                     :min_taken_date => since,
                                     :per_page => 500,
                                     :page => page)
      results.each {|r| photolist << r }
      size = results.size
      page += 1
    end

    ingest_photolist_for_user(photolist, user)
  end

  def self.ingest_photolist_for_user(photolist, user)
    photolist.each do |photo|
      ingest_photo_for_user(photo, user)
    end
  end

  def self.ingest_photo_for_user(photo,user)
    find_or_create_by_flickr_id(:flickr_id => photo.id,
                                :title => photo.title,
                                :description => photo.description,
                                :taglist => photo.tags,
                                :is_family => photo.isfamily,
                                :is_friend => photo.isfriend,
                                :is_public => photo.ispublic,
                                :thumb_url => photo.url_q,
                                :user_id => user.id,
                                :taken_at => DateTime.parse(photo.datetaken))
  end

  def self.taglist_from_tags(tags)
    tags.map do |t|
      if t =~ /\s/
        "\"#{t['raw']}\""
      else
        t['raw']
      end
    end.join(" ")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :nsid, :username, :fullname
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :flickr

  def require_user
    unless current_user
      redirect_to new_session_path
    end
  end

  def current_user
    return nil if session[:access_token].blank?
    @user = User.find_by_oauth_token(session[:access_token])
  end

  def flickr
    FlickRaw.api_key = ENV['FLICKR_API_KEY']
    FlickRaw.shared_secret = ENV['FLICKR_SHARED_SECRET']
    flickr = FlickRaw::Flickr.new
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :require_user
  
  def index
    @photos = current_user.photos.visible.order("taken_at DESC")
  end

  def alter
    updated_photos_count = 0
    params["photos"].each do |id, photo_hash|
      if photo_hash["update"] == "1"
        updated_photos_count += 1
        actual_photo = Photo.find(id)
        actual_photo.update_from_photo_hash(photo_hash)
        
        # update flickr
        FlickrFixer.perform_async(id, current_user.id)
      end
    end
    flash[:success] = "#{updated_photos_count} photos are being modified. Please check Flickr shortly to see their fixed tags."
    redirect_to photos_path
  end

  def ingest
    Photo.ingest_latest_for_user(current_user)
    flash[:success] = "Photos ingested!"
    redirect_to photos_path
  end

  def ingest_all
    Photo.ingest_all_for_user(current_user)
    flash[:success] = "Photos ingested!"
    redirect_to photos_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  FlickRaw.api_key = ENV['FLICKR_API_KEY']
  FlickRaw.shared_secret = ENV['FLICKR_SHARED_SECRET']

  def new
    flickr = FlickRaw::Flickr.new
    token = flickr.get_request_token(:oauth_callback => URI.escape("#{request.protocol}#{request.host_with_port}/session/callback"))
    # You'll need to store the token somewhere for when the user is returned to the callback method
    # I stick mine in memcache with their session key as the cache key
    session[:request_token] = token

    @auth_url = flickr.get_authorize_url(token['oauth_token'], :perms => 'write')
    redirect_to @auth_url
  end

  def callback
    flickr = FlickRaw::Flickr.new

    request_token = session[:request_token]
    oauth_token = params[:oauth_token]
    oauth_verifier = params[:oauth_verifier]

    raw_token = flickr.get_access_token(request_token['oauth_token'], request_token['oauth_token_secret'], oauth_verifier)
    # raw_token is a hash like this {"user_nsid"=>"92023420%40N00", "oauth_token_secret"=>"XXXXXX", "username"=>"boncey", "fullname"=>"Darren%20Greaves", "oauth_token"=>"XXXXXX"}
    # Use URI.unescape on the nsid and name parameters

    oauth_token = raw_token["oauth_token"]
    oauth_token_secret = raw_token["oauth_token_secret"]
    session[:access_token] = oauth_token
    session[:token_secret] = oauth_token_secret

    @user = User.find_or_create_by_oauth_token_and_oauth_token_secret(oauth_token, oauth_token_secret)
    if @user.username.blank?
      @user.update_attributes(:nsid => URI.unescape(raw_token['user_nsid']),
                              :username => raw_token['username'],
                              :fullname => URI.unescape(raw_token['fullname']))
    end

    # Store the oauth_token and oauth_token_secret in session or database
    #   and attach to a Flickraw instance before calling any methods requiring authentication

    # Attach the tokens to your flickr instance - you can now make authenticated calls with the flickr object
    flickr.access_token = oauth_token
    flickr.access_secret = oauth_token_secret

    Photo.ingest_latest_for_user(@user)
    redirect_to photos_path
  end

  def logout
    session[:access_secret] = nil
    session[:access_token] = nil
    redirect_to "/"
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    if current_user
      redirect_to photos_path
    else
      render :action => :about
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Instafix
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    .navbar-inverse.navbar
      .navbar-inner
        .container
          = link_to "Instafix", "/", :class => :brand
          %ul.nav
            %li= link_to "About", "/about"
          .details.pull-right
            - if session[:access_token]
              Logged in as
              %i= current_user.fullname
              = link_to "Log out", logout_session_path
            - else
              = link_to "Log in", new_session_path
    .container.main
      #flash
        - flash.each do |key, value|
          %div{:class => "alert alert-#{key}"}= value
      
      = yield

app/views/photos/index.html.haml
%h1 Instagram pictures on Flickr for #{current_user.fullname}

= form_tag(alter_photos_path, :method => :post) do |f|
  %p First, ingest your latest Instagram photographs from Flickr:
  %p
    - if current_user.photos.any?
      = link_to("Ingest new photos from Flickr", ingest_photos_path, :class => :btn)
      or
    = link_to("Ingest all photos from Flickr", ingest_all_photos_path, :class => :btn)


  - if @photos.any?
    %p Then, you might want to do the boring automatic tasks in one fell swoop: removing the Instagram tags from pictures (other than the automatic machine tag) and making sure that once photos are edited, they won't show up in Instafix again.

    %ul.actions
      %li= link_to "Remove all auto-added Instagram tags from tags.", "#", :id => "remove_instagram_tags"
      %li= link_to "Set all photos to be removed from Instafix after edit", "#", :id => "check_all"

    %p And finally, before you hit the "Update photos on Flickr" to push the updates to Flickr, you might want to update the titles, descriptions, and tags for individual pictures, below:

    %p
      = submit_tag("Update these photos on Flickr", :class => :btn)
      %ul.photos
        - for photo in @photos
          %li
            .row
              .span2= link_to image_tag(photo.thumb_url), photo.public_web_page
              .span10
                %fieldset
                  = fields_for 'photos[]', photo do |photo_fields|
                    = photo_fields.hidden_field :flickr_id
                    %h4= photo_fields.text_field :title
                    %p= photo_fields.text_area :description, :rows => 8 
                    %p= photo_fields.text_field :taglist, :class => "taglist"
                    %p
                      %label.checkbox
                        = photo_fields.check_box :is_hidden
                        Hide this photo in Instafix after update.
                    .hidden
                      %label.checkbox
                        = photo_fields.check_box :update, :class => "update_cb"
                        update this field?
        %p
          = submit_tag("Update these photos on Flickr", :class => :btn)